### ISSUE TITLE
Discriminator should be `u32`

### ISSUE THREAD

**Issue by steveluscher** [solana-program/loader-v4#4]
Looking through some transactions on mainnet, I think these discriminators are supposed to be `u32`.

https://github.com/solana-program/loader-v4/blob/main/program/idl.json#L36

**Comment by steveluscher** [comment]
Uh, actually nevermind. This program won't suffer from this because there _is_ no legacy version.

**Comment by buffalojoec** [comment]
There is a builtin version.
https://github.com/anza-xyz/agave/tree/master/programs/loader-v4
